services:
  backend:
    container_name: backend_api
    restart: always
    build: ./
    ports:
      - "${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
