services:
  backend:
    container_name: backend_api
    restart: always
    build: ./
    ports:
      - "${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}"
    #command:
    #  - python3 src/main.py
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
