services:
  backend:
    container_name: backend_api
    restart: always
    build: ./
    ports:
      - "${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}"
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
