services:
  backend:
    # image: backend
    container_name: backend_api
    restart: always
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
