name: "CI Workflow"
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install poetry"
        run: pipx install poetry==1.7.1

      - name: "Set Python 3.12"
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: "Install dependencies"
        run: poetry install --no-root --all-extras --with dev,api,lambda

      - name: "Lint"
        run: poetry run make lint
        continue-on-error: true

      - name: "Lint-ruff"
        run: poetry run make lint-ruff

  build-publish:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Log in to Ghcr"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.USERNAME}}
          password: ${{ secrets.GIT_PASSWORD}}

      - name: "Build and Push Docker Image - backend"
        run: |
          docker build -t ghcr.io/nikolinakonatarevic/pyproject/backend:${{ github.sha }} -f Dockerfile .
          docker push ghcr.io/nikolinakonatarevic/pyproject/backend:${{ github.sha }}




